apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello-task
  namespace: sample-app

spec:
  steps:
    - name: sayhello
      image: ubuntu
      command:
        - echo
      args:
        - "Hello World"