
name: Sample Api Pipeline

on:
#  push:
#    branches:
#      - task/*
#      - main
  workflow_dispatch:
    inputs:
      version:
        description: 'The target version to build'
        required: true

jobs:
  codeverify:
    name: Verify Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Unit Tests
        run: |
          echo 'Running Tests'

  dockerbuild:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v2    
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CREDENTIALS_AZURE }}
          allow-no-subscriptions: true

      - run: |
          az acr login --name acrsampleapidev
          docker build -t acrsampleapidev.azurecr.io/sampleapi:${{ github.event.inputs.version }} .
          docker push acrsampleapidev.azurecr.io/sampleapi:${{ github.event.inputs.version }}

          