# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Docker Approve

on:
  push:
    branches:
      - task/*
      - main
  workflow_dispatch:
    inputs:
      version:
        description: 'The target version to build'
        required: true

jobs:
  codebuild:
    runs-on: ubuntu-latest
    #if: github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v2
      - name: Run Unit Tests
        run: |
          echo 'Running Tests'

      - name: Create Artifact
        run: |
          dotnet publish -c Release -o ./artifacts

      - name: Zip Artifact
        run: |
          zip -r $GITHUB_WORKSPACE/artifacts.zip *.*
        working-directory: ./artifacts

      - name: Publish Artifact
        uses: actions/upload-artifact@v1
        with:
          name: assets-for-download
          path: ./artifact.zip

  #dockerbuild:
  #  runs-on: ubuntu-latest
  #  environment: development
  #  steps:
  #    - uses: actions/checkout@v2
  #    
  #    - name: Azure Login
  #      uses: azure/login@v1
  #      with:
  #        creds: ${{ secrets.CREDENTIALS_AZURE }}

  #    - run: |
  #        az acr login --name acrsampleapidev
  #        docker build -t acrsampleapidev.azurecr.io/sampleapi:v${{ github.event.inputs.version }} .
  #        docker push acrsampleapidev.azurecr.io/sampleapi:v${{ github.event.inputs.version }}

  #prod:
  #  runs-on: ubuntu-latest
  #  environment: production
  #  steps:
  #    - name: Azure Login
  #      uses: azure/login@v1
  #      with:
  #        creds: ${{ secrets.CREDENTIALS_AZURE }}

#      - run: |
#          az acr login --name acrsampleapidev
#          docker pull acrsampleapidev.azurecr.io/sampleapi:v${{ github.event.inputs.version }}
#
#          az acr login --name acrsampleapi
#          docker tag acrsampleapidev.azurecr.io/sampleapi:v${{ github.event.inputs.version }} acrsampleapi.azurecr.io/sampleapi:v${{ github.event.inputs.version }}
#          docker push acrsampleapi.azurecr.io/sampleapi:v${{ github.event.inputs.version }}
          