
name: OIDC workflow test
on:
  workflow_dispatch:

jobs:
  execute:
    name: Execute Flow
    runs-on: ubuntu-latest
    steps:
      - name: Script Step
        run: |
          echo "Hello World"
